#!/bin/bash

# loan-calc : script to calculate monthly loan payments

PROGNAME=$(basename $0)

usage () {
	cat <<- EOF
		Usage: $PROGNAME [-h help | -i interactive] PRINCIPAL INTEREST MONTHS

		Where:

		PRINCIPLE is the amount of the loan.
		INTEREST is the APR as a number (7% = 0.07).
		MONTHS is the length of the loan's term.
	EOF
}

# process command line options

if (($# != 3)); then

	interactive=

	while [[ -n $1 ]]; do

		case $1 in
			-h | --help)
																usage
																exit
																;;
			-i | --interactive)
																interactive=1
																;;
			*)
																usage >&2
																exit 1
																;;
		esac
		shift

	done

fi

# interactive mode

if [[ -n $interactive ]]; then

	while true; do

		read -p "Enter principal amount: " principal
		read -p "Enter interest as a number (e.g. 7% = 0.07): " interest
		read -p "Enter length of loan's term in months: " months
		break

	done

else

	principal=$1
	interest=$2
	months=$3

fi

bc <<- EOF
	scale = 10
	i = $interest / 12
	p = $principal
	n = $months
	a = p * ((i * ((1 + i)^n)) / (((1 + i)^n) - 1))
	print "\nMonthly Payment Amount\n"
	print "----------------------\n"
	print a, "\n"
EOF
